FROM node:20-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy frontend source code
COPY frontend/ ./

ENV NEXT_PUBLIC_API_URL=http://localhost:8000
ENV NEXT_PUBLIC_MAPTILER_API_KEY=CTTf1GnjFmqpYI0cPqIC
ENV PORT=3000

EXPOSE 3000

CMD ["npm", "run", "dev"]
